name: Update Toyota News

# Trigger manually or on schedule (9 UTC daily)
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3. Install dependencies
      - name: Install dependencies
        run: pip install requests beautifulsoup4

      # 4. Run scraper
      - name: Run Toyota news scraper
        run: python powerbi/news_scraper.py

      # 5. Commit updated JSON if changed
      - name: Commit and push updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add powerbi/toyota_news.json
          git diff --cached --quiet || git commit -m "Auto update Toyota news JSON"
          git push
