name: Update Toyota News

on:
  schedule:
    - cron: "0 9 * * *"  # every day at 9am UTC
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Toyota news scraper
        run: python news_scraper.py

      - name: Commit and push updated JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add powerbi/toyota_news.json
          git commit -m "Auto update Toyota news feed" || echo "No changes to commit"
          git push